services:
  nginx:
    image: nginx:1.25.1
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/www:/etc/nginx/www
    environment:
      GO_APP: go-app
      NODE_APP: node-app
  go-app:
    build:
      context: ./docker/go-app/
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
          - go-app
  node-app:
    build:
      context: ./docker/node-app
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
          - node-app
