version: "3"

services:
  nginx:
    image: nginx:1.25.1
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  go-app:
    build:
      context: ./docker/go-app/
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
          - go-app
